{% set name = "rank_filter" %}
{% set version = "0.4.15" %}
{% set checksum = "e5a3c6eb3a1c23e7a522221b54a7f96b5c38d4e47a4adf461c073f0ddacbf3d5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - toolchain
    - boost-cpp 1.66.0
    - python
    - setuptools >=18.0
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - cython >=0.23

  run:
    - boost-cpp 1.66.0
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]

test:
  source_files:
    - tests

  imports:
    - rank_filter

  commands:
    - python -m unittest discover -s .

about:
  home: https://github.com/nanshe-org/rank_filter
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'A simple python module containing an in-place linear rank filter optimized in C++.'

extra:
  recipe-maintainers:
    - jakirkham
