travis:
  secure:
    BINSTAR_TOKEN: oDenpZeZvvu36OJInRkMkXHzFZCmAfegFk7HqWoquxbNry8v/NBzbRJpBFXhHDwubeqoa7ewwwflQsLe5daS4wX3tanHpnXe423E9P0Bpjt1jPWqTbQiTE2nfSJUuMvgN09i06MuvuXMNtqhVjE6gflo9HkZCBa2K9fMg+fQQyqWfPSj2OQPJH4TroqjumeiyUPBVBj7Hp+3u2s24btRSpW/D0glSvkbcOOuQrR7YHzMSd8aP0itc/YgDgU+0MIFBkefWEzbWVC42T37zbEtIcvFo0Q/xUBH+m5cidFULP0ARmprCedLuF7F77N4bhfuNix/TIYnT8JXnRPBOLjr3AY9KBnkJm8MRazuOgAxXxksKYPenJfyffKk/mFKHKdRgB5URm8hLJhg2tWXrZOFyXDv6UzS2iecDJbIEzkNHRYzkDQm2ygZFId68cDNYC+6YeAxuHTz2d3sZTgugN7YAZCW3/zhDBk+7sfKRT67zgBb17vIsAuuon4hdCDYNZYYUl4t09Pi4BFmZdESxb0y4XOQHP/2fy4cH8fGmo2SLS4KuLZ97LltW5sBYO3urb9fh30Tvi7qNFrcTs2zPU6dt504pq5bRg/P5z3ykbtmpmO3KBZ4fKT8a8NXufUMy3zUa+/9lcfLw2mnYmwoKsuLsCBdovA+Ysu/QJ/1ktgcm/o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
